
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: vg

stages:
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: pubartifacet
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/index.php'
              ArtifactName: 'drop'
              publishLocation: 'Container'
    
      
  
  - stage: Directoty 
    displayName: Directoy listing
    jobs:
      - job: Deploy
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: "$(System.ArtifactsDirectory)/drop"
          
          - script: 
              pwd
              ls -ll
              echo "Artifact Staging Dir"
              ls -ll $(System.ArtifactStagingDirectory)
              echo "Artifact Directory"
              ls -ll $(System.ArtifactsDirectory)
          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh dev server'
              sourceFolder: "$(System.ArtifactsDirectory)/drop"
              contents: '**'
              targetFolder: '/root/azure/'
              readyTimeout: '20000'
          


