# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.1

stages:
    # Stage 3: Deploy
  - stage: Deploy
    displayName: Deploy Stage
#    dependsOn: Test
#    condition: succeeded()  # Only run if Test succeeds
    jobs:
      - job: DeployJob
        steps:
          - script: |
              echo "Name: $(name)"
              echo "Age: $(age)"
              echo "Hora: $(hora)"
            displayName: 'Deploy with Variables'