
trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Buiild
    displayName: Build Stage
    variables:
    - group: build
    jobs:
      - job: pubartifacet
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'  # Root source directory
              Contents: '**/*.php'  # Match all PHP files
              TargetFolder: '$(Build.ArtifactStagingDirectory)/build'  # Target staging directory

          - script: |
              cd $(Build.ArtifactStagingDirectory)
              zip -r build.zip build
              echo "ZIP file created: php-files.zip"
            displayName: Create ZIP File
          


          # Publish the PHP files as build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/build.zip'  # Publish from the staging directory
              ArtifactName: 'drop'
              publishLocation: 'Container'
          - script: |
              echo "build var is $(build)"
              echo "deploy var is $(deploy)"
    
      
  
  - stage: Deploy 
    displayName: Deploying Server
    variables:
    - group: deploy
    jobs:
      - job: Deploy
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: "$(System.ArtifactsDirectory)/drop"
          
          - script: |
              echo "build var is $(build)"
              echo "deploy var is $(deploy)"
              pwd
              ls -ll

          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh dev server'
              sourceFolder: "$(System.ArtifactsDirectory)/drop/"
              contents: '**'
              targetFolder: '/root/azure/'
              readyTimeout: '20000'
        
          - task: SSH@0
            inputs:
              sshEndpoint: 'ssh dev server'
              runOptions: 'commands'
              commands: 'mkdir /root/azure/ggggggggggggggggggggggggg'
              readyTimeout: '20000'
          
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Pay-As-You-Go(e0b04bb4-2704-41a6-894f-a1032232638a)'
              appType: 'webAppLinux'
              appName: 'fdfvdsffsdfsdfdsfdsfsdfdsfdsfdsfdsfsd'
              package: '$(System.ArtifactsDirectory)/drop/build.zip'
              runtimeStack: 'PHP|8.1'
  # - stage: AureAPP
  #   displayName: Azure app deployment
  #   jobs:
  #     - job: azureaapp
  #       steps:
  #         - checkout: none
          


