
trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Buiild
    displayName: Build Stage
    variables:
    - group: build
    jobs:
      - job: pubartifacet
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'  # Root source directory
              Contents: '**/*.php'  # Match all PHP files
              TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Target staging directory

          # Publish the PHP files as build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Publish from the staging directory
              ArtifactName: 'drop'
              publishLocation: 'Container'
    
      
  
  - stage: Deploy 
    displayName: Deploying Server
    variables:
    - group: deploy
    jobs:
      - job: Deploy
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: "$(System.ArtifactsDirectory)/drop"
          
          - script: |
              pwd
              ls -ll
              echo "Artifact Staging Dir"
              ls -ll $(System.ArtifactStagingDirectory)
              echo "Artifact Directory"
              ls -ll $(System.ArtifactsDirectory)
          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh dev server'
              sourceFolder: "$(System.ArtifactsDirectory)/drop"
              contents: '**'
              targetFolder: '/root/azure/'
              readyTimeout: '20000'
        
           
          
  # - stage: AureAPP
  #   displayName: Azure app deployment
  #   jobs:
  #     - job: azureaapp
  #       steps:
  #         - checkout: none
          


