trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: vg

stages:
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        steps:
          - script: |
              echo "Name: $(name)"
              echo "Age: $(age)"
              echo "Hora: $(hora)"
            displayName: 'Deploy with Variables'