
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: vg

stages:
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: pubartifacet
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          - script: ip a
    
      
  
  - stage: Directoty 
    displayName: Directoy listing
    jobs:
      - job: Deploy
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: "$(System.ArtifactStagingDirectory)"
          - script: ls -ll
          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh dev server'
              sourceFolder: "$(System.ArtifactsDirectory)/drop"
              contents: '**'
              targetFolder: '/root/azure/'
              readyTimeout: '20000'
          


